module Main (main) where

import Control.Applicative (asum, many, (<|>))
import Data.ByteString qualified as BS
import Data.Char (isDigit, isLetter)
import Data.List (stripPrefix)
import Text.Parsec qualified as P
import Text.Parsec.ByteString (Parser)

-------------------------------------------------------------------------------
-- "config"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- main
-------------------------------------------------------------------------------

main :: IO ()
main = do
    bs <- BS.readFile "bootstrap/imports.h"
    decls <- case P.parse (whitespace *> many declP <* P.eof) "imports.h" bs of
        Left err    -> print err >> fail "parse error"
        Right decls -> return decls

    -- low-level FFI module
    do
        let contents = ffiModule decls
        putStr contents
        writeFile "src/Clang/LowLevel/FFI.hs" contents

    do
        let contents = wrappers decls
        putStr contents
        writeFile "cbits/clang_wrappers_ffi.h" contents

-------------------------------------------------------------------------------
-- declarations
-------------------------------------------------------------------------------

data Decl
    = FunDecl Var [Var]
    | Comment String
  deriving Show

data Var = Var [String] String
  deriving Show

-------------------------------------------------------------------------------
-- parser
-------------------------------------------------------------------------------

whitespace :: Parser ()
whitespace = P.skipMany (P.satisfy (\c -> c == ' ' || c == '\n'))

lexeme :: Parser a -> Parser a
lexeme p = p <* whitespace

cident :: Parser String
cident = lexeme $ do
    h <- P.satisfy $ \c -> c == '_' || isLetter c
    t <- many $ P.satisfy $ \c -> c == '_' || isLetter c || isDigit c
    return (h : t)

-- pointers are only recognised when they are surrounded by whitespace
pointer :: Parser Char
pointer = lexeme (P.char '*')

pointerS :: Parser String
pointerS = (:[]) <$> pointer

varDecl :: Parser Var
varDecl = do
    x <- cident <|> pointerS
    y <- cident <|> pointerS
    go (x :) y
  where
    go :: ([String] -> [String]) -> String -> Parser Var
    go xs y = ((cident <|> pointerS) >>= \z -> go (xs . (y : )) z) <|> return (Var (xs []) y)

paramP :: Parser Var
paramP = varDecl

paramListP :: Parser [Var]
paramListP = asum [
      -- an empty parameter list is indicated by a single void keyword
      [] <$ lexeme (P.string "void")
      -- otherwise, parameters are separated by commas
    , paramP `P.sepBy` lexeme (P.char ',')
    ]

funDeclP :: Parser Decl
funDeclP = do
    fun <- varDecl
    _ <- lexeme (P.char '(')
    args <- paramListP
    _ <- lexeme (P.char ')')
    _ <- lexeme (P.char ';')
    return (FunDecl fun args)

commentP :: Parser Decl
commentP = do
    _ <- P.string "//"
    comment <- many $ P.satisfy $ \c -> c /= '\n'
    _ <- lexeme (P.char '\n')
    return (Comment comment)

declP :: Parser Decl
declP = P.choice
    [ funDeclP
    , commentP
    ]

-------------------------------------------------------------------------------
-- Haskell FFI
-------------------------------------------------------------------------------

ffiModule :: [Decl] -> String
ffiModule ds = unlines $
    header ++
    concatMap ffiDecl ds
  where
    header :: [String]
    header =
        [ "{-| this module is autogenerated with cabal run clang-bootstrap -}"
        , "module Clang.LowLevel.FFI (module Clang.LowLevel.FFI) where"
        , ""
        , "import Clang.Enum.Simple"
        , "import Clang.Internal.ByValue"
        , "import Clang.Internal.ConstPtr"
        , "import Clang.LowLevel.Core.Enums"
        , "import Clang.LowLevel.Core.Pointers"
        , "import Clang.LowLevel.Core.Structs"
        , "import Foreign.C.Types"
        , "import Foreign.Ptr"
        , ""
        ]

ffiDecl :: Decl -> [String]
ffiDecl (Comment comment) =
    [ "--" ++ comment
    , ""
    ]
ffiDecl (FunDecl (Var rtype name) args)
    | isStruct rtype
    =
    [ "foreign import capi unsafe \"clang_wrappers.h" ++ ffiName ++ "\""
    , "  " ++ name' ++ " :: " ++ foldr argumentTy (toHaskellType Res rtype) args ++ " -> IO ()"
    , ""
    ]

    | otherwise
    =
    [ "foreign import capi unsafe \"clang_wrappers.h" ++ ffiName ++ "\""
    , "  " ++ name' ++ " :: " ++ foldr argumentTy (ioType (toHaskellType Res rtype)) args
    , ""
    ]
  where
    -- name in C
    ffiName
        | isStruct rtype || any isStructVar args
        = ""

        | otherwise
        = " " ++ name

    -- name in Haskell
    name'
        | isStruct rtype || any isStructVar args
        = case stripPrefix "clang_" name of
            Nothing  -> error $ name ++ " doesn't start with clang_"
            Just sfx -> "wrap_" ++ sfx

        | otherwise
        =  case stripPrefix "clang_" name of
            Nothing  -> error $ name ++ " doesn't start with clang_"
            Just sfx -> "nowrapper_" ++ sfx

    argumentTy :: Var -> String -> String
    argumentTy (Var ty _) rest = toHaskellType Arg ty ++ " -> " ++ rest

ioType :: String -> String
ioType ty = if any (== ' ') ty then "IO (" ++ ty ++ ")" else "IO " ++ ty

-------------------------------------------------------------------------------
-- (wrapper) Header generation
-------------------------------------------------------------------------------

wrappers :: [Decl] -> String
wrappers ds = unlines $
    header ++
    concatMap wrapDecl ds
  where
    header :: [String]
    header =
        [ "/* this header is autogenerated with cabal run clang-bootstrap */"
        ]

wrapDecl :: Decl -> [String]
wrapDecl (Comment comment) =
    [ "/*" ++ comment ++ " */"
    , ""
    ]
wrapDecl (FunDecl (Var rtype rname) args)
    | isStruct rtype
    =
    [ "static inline void " ++ rname' ++ "(" ++ foldr argumentTy (toCType Res rtype ++ " result") args ++ ") {"
    , "  *result = " ++ rname ++ "(" ++ foldr callArg "" args ++ ");"
    , "}"
    , ""
    ]

    | any isStructVar args
    =
    [ "static inline " ++ toCType Res rtype ++ " " ++ rname' ++ "(" ++ foldr argumentTy "" args ++ ") {"
    , "  return " ++ rname ++ "(" ++ foldr callArg "" args ++ ");"
    , "}"
    , ""
    ]

    | otherwise
    =
    []
  where
    rname' = case stripPrefix "clang_" rname of
        Nothing  -> error $ rname ++ " doesn't start with clang_"
        Just sfx -> "wrap_" ++ sfx

    argumentTy :: Var -> String -> String
    argumentTy (Var atype aname) rest = commaArg (toCType Arg atype ++ " " ++ aname) rest

    callArg :: Var -> String -> String
    callArg (Var atype aname) rest
        | isStruct atype = commaArg ("*" ++ aname) rest
        | otherwise      = commaArg aname rest

commaArg :: String -> String -> String
commaArg x "" = x
commaArg x y  = x ++ ", " ++ y

-------------------------------------------------------------------------------
-- Utilities
-------------------------------------------------------------------------------

isStruct :: [String] -> Bool
isStruct ["CXType"]           = True
isStruct ["CXString"]         = True
isStruct ["CXCursor"]         = True
isStruct ["CXSourceLocation"] = True
isStruct ["CXSourceRange"]    = True
isStruct ["CXToken"]          = True
isStruct _                    = False

isStructVar :: Var -> Bool
isStructVar (Var ty _) = isStruct ty

-- | result or argument
data RA = Res | Arg

haskellRA :: RA -> String
haskellRA Res = "W "
haskellRA Arg = "R "

toHaskellType :: RA -> [String] -> String
toHaskellType ra ["CXType"]                 = haskellRA ra ++ "CXType_"
toHaskellType ra ["CXString"]               = haskellRA ra ++ "CXString_"
toHaskellType ra ["CXCursor"]               = haskellRA ra ++ "CXCursor_"
toHaskellType _  ["CXCursor", "*"]          = "Ptr CXCursor_"
toHaskellType _  ["CXFile"]                 = "CXFile"
toHaskellType _  ["CXFile", "*"]            = "Ptr CXFile"
toHaskellType _  ["CXTranslationUnit"]      = "CXTranslationUnit" -- typedef to a pointer, not a struct.
toHaskellType _  ["enum","CXCursorKind"]    = "SimpleEnum CXCursorKind"
toHaskellType _  ["enum","CXTypeKind"]      = "SimpleEnum CXTypeKind"
toHaskellType _  ["enum"
                 ,"CXLinkageKind"]          = "SimpleEnum CXLinkageKind"
toHaskellType _  ["enum"
                 ,"CXVisibilityKind"]       = "SimpleEnum CXVisibilityKind"
toHaskellType _  ["enum"
                 ,"CXAvailabilityKind"]     = "SimpleEnum CXAvailabilityKind"
toHaskellType _  ["CXPrintingPolicy"]       = "CXPrintingPolicy"
toHaskellType _  ["long","long"]            = "CLLong"
toHaskellType _  ["unsigned","long","long"] = "CULLong"
toHaskellType _  ["unsigned"]               = "CUInt"
toHaskellType _  ["unsigned", "*"]          = "Ptr CUInt"
toHaskellType _  ["int"]                    = "CInt"
toHaskellType _  ["void"]                   = "()"
toHaskellType _  ["const", "char", "*"]     = "ConstPtr CChar"
toHaskellType _  ["CXDiagnostic"]           = "CXDiagnostic"
toHaskellType ra ["CXSourceLocation"]       = haskellRA ra ++ "CXSourceLocation_"
toHaskellType _  ["CXString", "*"]          = "W CXString_"
toHaskellType ra ["CXSourceRange"]          = haskellRA ra ++ "CXSourceRange_"
toHaskellType _  ["CXSourceRange", "*"]     = "W CXSourceRange_"
toHaskellType _  ["CXDiagnosticSet"]        = "CXDiagnosticSet"
toHaskellType _  ["enum", "CXDiagnosticSeverity"]
                                            = "SimpleEnum CXDiagnosticSeverity"
toHaskellType _  ["CXIndex"]                = "CXIndex"
toHaskellType _  ["const", "char", "*", "const", "*"]
                                            = "ConstPtr (ConstPtr CChar)"
toHaskellType _  ["struct", "CXUnsavedFile", "*"]
                                            = "Ptr CXUnsavedFile"
toHaskellType _  ["CXTranslationUnit", "*"] = "Ptr CXTranslationUnit"
toHaskellType _  ["enum", "CXErrorCode"]    = "SimpleEnum (Maybe CXErrorCode)"
toHaskellType _  ["CXTargetInfo"]           = "CXTargetInfo"
toHaskellType _  ["enum", "CXTLSKind"]      = "SimpleEnum CXTLSKind"
toHaskellType _  ["CXCursorVisitor"]        = "CXCursorVisitor"
toHaskellType _  ["CXEvalResult"]           = "CXEvalResult"
toHaskellType _  ["CXEvalResultKind"]       = "SimpleEnum CXEvalResultKind"
toHaskellType _  ["double"]                 = "CDouble"
toHaskellType ra ["CXToken"]                = haskellRA ra ++ "CXToken_"
toHaskellType _  ["CXToken", "*"]           = "Ptr CXToken_"
toHaskellType _  ["CXToken", "*", "*"]      = "Ptr (Ptr CXToken_)"
toHaskellType _  ["CXTokenKind"]            = "SimpleEnum CXTokenKind"
toHaskellType _  ["enum", "CX_StorageClass"]
                                            = "SimpleEnum CX_StorageClass"
toHaskellType _ ty                          = error $ "Unknown type " ++ unwords ty

cRA :: RA -> String
cRA Res = ""
cRA Arg = "const "

toCType :: RA -> [String] -> String
toCType ra ["CXType"]                 = cRA ra ++ "CXType*"
toCType ra ["CXString"]               = cRA ra ++ "CXString*"
toCType ra ["CXCursor"]               = cRA ra ++ "CXCursor*"
toCType ra ["CXCursor", "*"]          = cRA ra ++ "CXCursor*"
toCType _  ["CXFile"]                 = "CXFile"
toCType _  ["CXFile", "*"]            = "CXFile *"
toCType _  ["CXTranslationUnit"]      = "CXTranslationUnit"
toCType _  ["enum","CXCursorKind"]    = "enum CXCursorKind"
toCType _  ["enum","CXTypeKind"]      = "enum CXTypeKind"
toCType _  ["enum"
           ,"CXLinkageKind"]          = "enum CXLinkageKind"
toCType _  ["enum"
           ,"CXVisibilityKind"]       = "enum CXVisibilityKind"
toCType _  ["enum"
           ,"CXAvailabilityKind"]     = "enum CXAvailabilityKind"
toCType _  ["CXPrintingPolicy"]       = "CXPrintingPolicy"
toCType _  ["long","long"]            = "long long"
toCType _  ["unsigned","long","long"] = "unsigned long long"
toCType _  ["unsigned"]               = "unsigned"
toCType _  ["unsigned", "*"]          = "unsigned *"
toCType _  ["int"]                    = "int"
toCType _  ["void"]                   = "void"
toCType _  ["const", "char", "*"]     = "const char *"
toCType _  ["CXDiagnostic"]           = "CXDiagnostic"
toCType ra ["CXSourceLocation"]       = cRA ra ++ "CXSourceLocation*"
toCType _  ["CXString", "*"]          = "CXString*"
toCType ra ["CXSourceRange"]          = cRA ra ++ "CXSourceRange*"
toCType _  ["CXSourceRange", "*"]     = "CXSourceRange*"
toCType _  ["CXDiagnosticSet"]        = "CXDiagnosticSet"
toCType _  ["enum", "CXDiagnosticSeverity"]
                                      = "enum CXDiagnosticSeverity"
toCType _  ["CXIndex"]                = "CXIndex"
toCType _  ["const", "char", "*", "const", "*"]
                                      = "const char * const *"
toCType _  ["struct", "CXUnsavedFile", "*"]
                                      = "CXUnsavedFile *"
toCType _  ["CXTranslationUnit", "*"] = "CXTranslationUnit *"
toCType _  ["enum", "CXErrorCode"]    = "enum CXErrorCode"
toCType _  ["CXTargetInfo"]           = "CXTargetInfo"
toCType _  ["enum", "CXTLSKind"]      = "enum CXTLSKind"
toCType _  ["CXCursorVisitor"]        = "CXCursorVisitor"
toCType _  ["CXEvalResult"]           = "CXEvalResult"
toCType _  ["CXEvalResultKind"]       = "CXEvalResultKind"
toCType _  ["double"]                 = "double"
toCType ra ["CXToken"]                = cRA ra ++ "CXToken *"
toCType _  ["CXToken", "*"]           = "CXToken *"
toCType _  ["CXToken", "*", "*"]      = "CXToken * *"
toCType _  ["CXTokenKind"]            = "CXTokenKind"
toCType _  ["enum", "CX_StorageClass"]
                                      = "enum CX_StorageClass"
toCType _ ty                          = error $ "Unknown type " ++ unwords ty
