name: libclang (Ubuntu)
description: Build on Ubuntu

# If needed, we can SSH into the machine executing the job and
# figure out what's going on:
# - name: Setup tmate session
#   uses: mxschmitt/action-tmate@v3

runs:
  using: composite
  steps:
    - name: Configure environment variables
      shell: bash
      run: |
        export LD_LIBRARY_PATH=${{ github.workspace }}/manual/c/:$LD_LIBRARY_PATH
        echo $LD_LIBRARY_PATH
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

    - name: Build
      shell: bash
      run: cabal build all
